import logfire
from fastapi import FastAPI, HTTPException
from contextlib import asynccontextmanager

from core.config import settings
from core.observability import setup_observability
from db.session import init_db_pool, close_db_pool
from db.schema import initialize_schema

from models.api import ChatRequest, ChatResponse
from agents.router import router_agent
from agents.workers import worker_registry, init_workers

# Setup logfire immediately
setup_observability()

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup actions
    logfire.info("Starting up Agent Router API...")
    await init_db_pool()
    await initialize_schema()
    await init_workers()
    yield
    # Shutdown actions
    logfire.info("Shutting down Agent Router API...")
    await close_db_pool()

app = FastAPI(title=settings.app_name, lifespan=lifespan)
logfire.instrument_fastapi(app)

@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(req: ChatRequest):
    logfire.info(f"Received chat request: session_id={req.session_id}")
    
    try:
        # 1. Ask the Router Agent, passing the dynamically loaded agent names
        router_result = await router_agent.run(req.message, deps=list(worker_registry.keys()))
        router_response = router_result.output
        
        if router_response.should_delegate and router_response.target_agent in worker_registry:
            # 2. Delegate to worker agent
            target_worker = worker_registry[router_response.target_agent]
            logfire.info(f"Delegating task to worker agent: {router_response.target_agent}")
            
            # The delegated instruction string is generated by the router as 'final_response'
            worker_result = await target_worker.run(
                router_response.final_response, 
                deps=router_response.target_agent
            )
            
            return ChatResponse(
                response=worker_result.output,
                agent_used=router_response.target_agent
            )
        else:
            return ChatResponse(
                response=router_response.final_response,
                agent_used="router"
            )
            
    except Exception as e:
        logfire.error(f"Error processing chat request: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
