import logfire
from fastapi import APIRouter, HTTPException, Request
from models.api import ChatRequest, ChatResponse
from agents.router import router_agent
from models.dependencies import RouterDependencies, AgentDependencies

router = APIRouter()

@router.post("", response_model=ChatResponse)
async def chat_endpoint(req: ChatRequest, request: Request):
    logfire.info(f"Received chat request: session_id={req.session_id}")
    
    # Inject application dependencies from FastAPI state
    pool = request.app.state.pool
    worker_registry = request.app.state.worker_registry
    
    try:
        # 1. Ask the Router Agent, passing the dynamically loaded agent names via struct
        router_deps = RouterDependencies(
            available_agents=list(worker_registry.keys()), 
            db_pool=pool
        )
        router_result = await router_agent.run(req.message, deps=router_deps)
        router_response = router_result.output
        
        if router_response.should_delegate and router_response.target_agent in worker_registry:
            # 2. Delegate to worker agent
            target_worker = worker_registry[router_response.target_agent]
            logfire.info(f"Delegating task to worker agent: {router_response.target_agent}")
            
            # Create strict Worker dependencies
            worker_deps = AgentDependencies(
                agent_name=router_response.target_agent, 
                db_pool=pool
            )
            
            # The delegated instruction string is generated by the router as 'final_response'
            worker_result = await target_worker.run(
                router_response.final_response, 
                deps=worker_deps
            )
            
            return ChatResponse(
                response=worker_result.output,
                agent_used=router_response.target_agent
            )
        else:
            return ChatResponse(
                response=router_response.final_response,
                agent_used="router"
            )
            
    except Exception as e:
        logfire.error(f"Error processing chat request: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
